name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PEM file for SSH
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Debug secret
        run: echo "Image = ${{ secrets.DOCKER_HUB_USERNAME }}/1-load-test-fe:latest"    

      - name: Pull and run Docker image on server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_SERVER_HOST }} "
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/1-load-test-fe:latest
            docker stop 1-load-test-fe || true
            docker rm 1-load-test-fe || true
            docker run -d --name 1-load-test-fe -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/1-load-test-fe:latest
          "